-- Alter Kitap
ALTER TABLE Tbl_Kitap
ADD CONSTRAINT TurID
FOREIGN KEY (TurID) REFERENCES Tbl_Tur(TurID)

ALTER TABLE Tbl_Kitap
ADD CONSTRAINT YazarID
FOREIGN KEY (YazarID) REFERENCES Tbl_Yazar(YazarID)

-- Alter Islem
ALTER TABLE Tbl_Islem
ADD CONSTRAINT OgrenciID
FOREIGN KEY (OgrenciID) REFERENCES Tbl_Ogrenci(OgrenciID)

ALTER TABLE Tbl_Islem
ADD CONSTRAINT KitapID
FOREIGN KEY (KitapID) REFERENCES Tbl_Kitap(KitapID)

-- Alte Öğrenci
ALTER TABLE Tbl_Ogrenci
ADD CONSTRAINT BolumID
FOREIGN KEY (BolumID) REFERENCES Tbl_Bolum(BolumID)