//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ders39_HtmlDersleri_NORTHWND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_urunleri_listele
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public string CategoryName { get; set; }
        public string CompanyName { get; set; }
    }
}
